@UT.MicroserviceEco.OrderService_HostAddress = http://localhost:5200

#if (EnableOpenAPI)
GET {{UT.MicroserviceEco.OrderService_HostAddress}}/openapi/v1.json
Accept: application/json

###
#endif

GET {{UT.MicroserviceEco.OrderService_HostAddress}}/weatherforecast/
Accept: application/json

###
